import numpy as np
InputA = int(input("SIZE A HERE "))
InputB = int(input("SIZE B HERE "))
InputC = int(input("SIZE C HERE "))
A = np.random.randint(1, 100000, size=(InputA))
B = np.random.randint(1, 100000, size=(InputB))
C = np.random.randint(1, 100000000, size=(InputC))
resultAC = list(set(A) & set(C))
resultBC = list(set(B) & set(C))
Likes = len(resultAC)
Dislikes = len(resultBC)
print(Likes - Dislikes)
